// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAdministrativo.Data;

namespace SistemaAdministrativo.Migrations
{
    [DbContext(typeof(IgrejaContext))]
    [Migration("20210329125345_IgrejaMinisterio")]
    partial class IgrejaMinisterio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("SistemaAdministrativo.Models.Cadastro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComunCongregcao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdIgreja")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IgrejaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profissao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rg")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId");

                    b.ToTable("Cadastros");
                });

            modelBuilder.Entity("SistemaAdministrativo.Models.Igreja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BairroIgreja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatadaAbertura")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdLivro")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LivroId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("Igrejas");
                });

            modelBuilder.Entity("SistemaAdministrativo.Models.IgrejaMinisterio", b =>
                {
                    b.Property<Guid>("igrejaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MinisterioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("igrejaId", "MinisterioId");

                    b.HasIndex("MinisterioId");

                    b.ToTable("IgrejaMinisterios");
                });

            modelBuilder.Entity("SistemaAdministrativo.Models.Livro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IgrejaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NumerodoLivro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("SistemaAdministrativo.Models.LivroCadastro", b =>
                {
                    b.Property<Guid>("LivroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CadastroId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LivroId", "CadastroId");

                    b.HasIndex("CadastroId");

                    b.ToTable("LivroCadastros");
                });

            modelBuilder.Entity("SistemaAdministrativo.Models.Ministerio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataOrdenacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ministerio");
                });

            modelBuilder.Entity("SistemaAdministrativo.Models.Cadastro", b =>
                {
                    b.HasOne("SistemaAdministrativo.Models.Igreja", "Igreja")
                        .WithMany()
                        .HasForeignKey("IgrejaId");

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("SistemaAdministrativo.Models.Igreja", b =>
                {
                    b.HasOne("SistemaAdministrativo.Models.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroId");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("SistemaAdministrativo.Models.IgrejaMinisterio", b =>
                {
                    b.HasOne("SistemaAdministrativo.Models.Ministerio", "Ministerio")
                        .WithMany("IgrejaMinisterios")
                        .HasForeignKey("MinisterioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAdministrativo.Models.Igreja", "Igreja")
                        .WithMany("IgrejaMinisterios")
                        .HasForeignKey("igrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");

                    b.Navigation("Ministerio");
                });

            modelBuilder.Entity("SistemaAdministrativo.Models.Livro", b =>
                {
                    b.HasOne("SistemaAdministrativo.Models.Igreja", null)
                        .WithMany("Livros")
                        .HasForeignKey("IgrejaId");
                });

            modelBuilder.Entity("SistemaAdministrativo.Models.LivroCadastro", b =>
                {
                    b.HasOne("SistemaAdministrativo.Models.Cadastro", "Cadastro")
                        .WithMany("LivroCadastros")
                        .HasForeignKey("CadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAdministrativo.Models.Livro", "Livro")
                        .WithMany("LivroCadastros")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cadastro");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("SistemaAdministrativo.Models.Cadastro", b =>
                {
                    b.Navigation("LivroCadastros");
                });

            modelBuilder.Entity("SistemaAdministrativo.Models.Igreja", b =>
                {
                    b.Navigation("IgrejaMinisterios");

                    b.Navigation("Livros");
                });

            modelBuilder.Entity("SistemaAdministrativo.Models.Livro", b =>
                {
                    b.Navigation("LivroCadastros");
                });

            modelBuilder.Entity("SistemaAdministrativo.Models.Ministerio", b =>
                {
                    b.Navigation("IgrejaMinisterios");
                });
#pragma warning restore 612, 618
        }
    }
}
