// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAdministrativo.Data;

namespace SistemaAdministrativo.Migrations
{
    [DbContext(typeof(IgrejaContext))]
    partial class IgrejaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("SistemaAdministrativo.Models.Cadastro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComunCongregcao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IgrejaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profissao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rg")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId");

                    b.ToTable("Cadastros");
                });

            modelBuilder.Entity("SistemaAdministrativo.Models.Igreja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BairroIgreja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatadaAbertura")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdLivro")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LivrosId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LivrosId");

                    b.ToTable("Igrejas");
                });

            modelBuilder.Entity("SistemaAdministrativo.Models.Livro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CadastroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCadastro")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NumerodoLivro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CadastroId");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("SistemaAdministrativo.Models.Cadastro", b =>
                {
                    b.HasOne("SistemaAdministrativo.Models.Igreja", "Igreja")
                        .WithMany()
                        .HasForeignKey("IgrejaId");

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("SistemaAdministrativo.Models.Igreja", b =>
                {
                    b.HasOne("SistemaAdministrativo.Models.Livro", "Livros")
                        .WithMany()
                        .HasForeignKey("LivrosId");

                    b.Navigation("Livros");
                });

            modelBuilder.Entity("SistemaAdministrativo.Models.Livro", b =>
                {
                    b.HasOne("SistemaAdministrativo.Models.Cadastro", "Cadastro")
                        .WithMany()
                        .HasForeignKey("CadastroId");

                    b.Navigation("Cadastro");
                });
#pragma warning restore 612, 618
        }
    }
}
